# Dependabot set up for three package managers: GitHub Actions.

version: 2
updates:

  # Maintain dependencies for GitHub Actions.
  - package-ecosystem: "github-actions"
    # Files stored in repository root.
    directory: "/"
    schedule:
      # Check for updates every weekday.
      interval: "daily"
    open-pull-requests-limit: 10
